title: Neko Docs Archive
description: 네코랜드 독스 아카이브
baseurl: "/neko-docs-archive" # the subpath of your site, e.g. /blog
url: "https://vin-spiegel.github.io" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"
, "docs/tests/"
]

# 기본적으로 /docs/tests의 페이지는 ste가 빌드될 때 제외됩니다.
# 포함하려면 위의 관련 줄을 주석 처리하십시오.
# 다음 줄의 주석 해제는 작동하지 않습니다 - https://github.com/jekyll/jekyll/issues/4791 참조
# include: ["docs/tests/"]

# 로고 이미지
# logo: "/assets/images/just-the-docs.png"

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # 개별적으로 검색할 수 있는 섹션으로 페이지 분할
  # 1 - 6 지원, 기본값: 2
  heading_level: 2
  # 검색 결과당 최대 미리보기 수  
  # Default: 3
  previews: 2
  # 미리보기에서 일치하는 단어 앞에 표시할 최대 단어 수
  preview_words_before: 3
  # 미리보기에서 일치하는 단어 뒤에 표시할 최대 단어 수 Default: 10
  preview_words_after: 3
  # 검색 토큰 구분 기호 설정
  # 기본값: /[\s\-/]+/
  # 예: 하이픈으로 연결된 검색어 지원 활성화
  tokenizer_separator: /[\s/]+/
  # 검색 결과에 상대 URL 표시
  # true(기본값) 또는 false 지원
  rel_url: true
  # 모든 페이지의 오른쪽 하단에 나타나는 검색 버튼을 활성화 또는 비활성화합니다.
  # Supports true or false (default)
  button: true

# Enable or disable heading anchors
heading_anchors: true

# 오른쪽 상단 aux 링크
aux_links:
  "GitHub":
    - "//github.com/vin-spiegel/neko-docs-archive"
aux_links_new_tab: true


# Sort order for navigation links
# default, equivalent to nil
# Capital letters sorted before lowercase
# nav_sort: case_sensitive 

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "위로 가기"

footer_content: "Generated by Spiegel"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html



# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "이 페이지 편집하기"
gh_edit_repository: "https://github.com/vin-spiegel/neko-docs-archive" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: dark

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
ga_tracking: UA-2709176-10
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
